name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          debug: true
          host: 54.39.16.154
          username: ynov
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            docker stop grp2-app || true
            docker rm grp2-app || true
            cd /home/ynov/grp2/front
            git pull
            docker build -t grp2-app .
            docker run -d --name grp2-app -p 80:80 grp2-app
